import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data=pd.DataFrame([
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','no','no','no','no','yes','no','yes','yes','yes',30,'Female',150,'Chandanasava','Khadirarishta','Mustakarishta'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','yes','yes','yes','no','yes','no','no','yes','no','no',60,'Male',136,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatryasava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjunarishta'],
['no','yes','no','yes','no','yes','no','no','no','no','yes',47,'Female',77,'Dhatrysava','Pippalyasavam','Jeerakarishtam'],
['yes','no','yes','no','yes','no','no','no','no','no','no',25,'Male',65,'Ayaskriti','Palashpushpasava','Pippalyasavam'],
['no','yes','no','yes','no','no','no','no','yes','no','yes',32,'Female',58,'Chandanasava','Kutajarishta','Arjunarishta'],
['no','no','yes','no','no','yes','no','no','no','no','yes',45,'Male',72,'Kalmeghasava','Angoorasava','Drakshasava'],
['yes','yes','yes','no','no','no','no','yes','no','no','no',38,'Female',61,'Saraswatarishta','Mrigamadasava','Raktshodhakarishta'],
['yes','no','yes','yes','no','yes','yes','no','yes','yes','no',42,'Male',77,'Dhatryasava','Dasamoolarishtam','Punarnavasavam'],
['no','no','yes','no','yes','no','yes','no','no','no','no',34,'Female',63,'Babularishta','Takrarishta','Balamritam'],
['yes','no','no','yes','no','no','no','no','no','no','yes',37,'Male',72,'Ashwagandha','Lohasava','Vasarishta & Vasasava'],
['no','yes','yes','yes','yes','no','no','yes','no','yes','yes',40,'Female',69,'Neem','Arvindasava','Punarnavarishta'],
['yes','no','no','yes','no','yes','no','no','no','no','no',48,'Male',73,'Ayaskriti','Dashamoola Jeerakam','Karpoorasava'],
['no','no','yes','no','no','no','yes','no','yes','no','no',33,'Female',63,'Chandanasava','Khadirarishta','Mustakarishta'],
['yes','yes','yes','no','yes','no','no','yes','no','no','yes',31,'Male',68,'Raktshodhakarishta','Vidangarishta','Arjun']
],columns=['Cold','Eyepain','Fever','Headache','Stomachache','Dizziness','Vomiting','Chestpain','Jointpain','Loosemotion','Throatinfection','Age','Gender','Weight','Ayurvedic Medicine','Ayurvedic Medicine1','Ayurvedic Medicine2'])

data.replace({'yes': 0, 'no': 1}, inplace=True)

# Encode 'Male' and 'Female' as 3 and 4
data.replace({'Male': 3, 'Female': 4}, inplace=True)

# Separate features and targets
features = data.drop(columns=['Ayurvedic Medicine', 'Ayurvedic Medicine1', 'Ayurvedic Medicine2'])
targets = data[['Ayurvedic Medicine', 'Ayurvedic Medicine1', 'Ayurvedic Medicine2']]

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

# Build the Random Forest Classifier model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model to the training data
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate accuracy for each output variable
accuracies = []
for i in range(targets.shape[1]):
    accuracy = accuracy_score(y_test.iloc[:, i], y_pred[:, i])
    accuracies.append(accuracy)

# Compute the average accuracy
average_accuracy = (sum(accuracies) / len(accuracies))*100

# Print the average accuracy
print("Average Accuracy:", average_accuracy,' %')


user_input = input("Enter the values (comma-separated): ")
user_input_list = user_input.split(',')

# Create a DataFrame from the user input
user_input_dict = {
    'Cold': int(user_input_list[0]),
    'Eyepain': int(user_input_list[1]),
    'Fever': int(user_input_list[2]),
    'Headache': int(user_input_list[3]),
    'Stomachache': int(user_input_list[4]),
    'Dizziness': int(user_input_list[5]),
    'Vomiting': int(user_input_list[6]),
    'Chestpain': int(user_input_list[7]),
    'Jointpain': int(user_input_list[8]),
    'Loosemotion': int(user_input_list[9]),
    'Throatinfection': int(user_input_list[10]),
    'Age': int(user_input_list[11]),
    'Gender': int(user_input_list[12]),
    'Weight': int(user_input_list[13])
}

user_input_df = pd.DataFrame([user_input_dict])

# Make predictions on the user input
user_output = model.predict(user_input_df)

# Decode the predictions
user_output_decoded = pd.DataFrame(user_output, columns=['Ayurvedic Medicine', 'Ayurvedic Medicine1', 'Ayurvedic Medicine2'])
user_output_decoded.replace({0: 'yes', 1: 'no'}, inplace=True)
user_output_decoded.replace({3: 'Male', 4: 'Female'}, inplace=True)

# Extract the predicted values
medicine1 = user_output_decoded['Ayurvedic Medicine'][0]
medicine2 = user_output_decoded['Ayurvedic Medicine1'][0]
medicine3 = user_output_decoded['Ayurvedic Medicine2'][0]

# Print the predicted values
print("Predicted Ayurvedic Medicine 1:", medicine1)
print("Predicted Ayurvedic Medicine 2:", medicine2)
print("Predicted Ayurvedic Medicine 3:", medicine3)